# Generated by Django 5.1.2 on 2024-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HerSupport', '0002_remove_post_author_biomarker_delete_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
